
export interface Subject {
  title: string;
  description: string;
  keywords: string[];
  url: string;
  subject: string;
  cheatsheetName: string;
  markdownFile: string;
}

export const subjects: { [key: string]: Subject } = {
  angular: {
    title: "Angular Framework Cheatsheet",
    description: "Comprehensive Angular framework guide with components, services, routing, forms, and best practices.",
    keywords: ["angular", "typescript", "web framework", "spa", "frontend"],
    url: "https://learn.codeunia.com/angular",
    subject: "Angular",
    cheatsheetName: "Angular Framework Cheatsheet",
    markdownFile: "angular.md",
  },
  c: {
    title: "C Programming Cheatsheet",
    description: "Comprehensive C programming guide with syntax, pointers, memory management, and system programming.",
    keywords: ["c programming", "pointers", "memory management", "system programming", "low level"],
    url: "https://learn.codeunia.com/c",
    subject: "C",
    cheatsheetName: "C Programming Cheatsheet",
    markdownFile: "c.md",
  },
  cpp: {
    title: "C++ Programming Cheatsheet — Codeunia",
    description: "Master C++ programming with STL, memory management, and performance optimization. Complete C++ reference guide.",
    keywords: ["cpp", "c++", "programming", "stl", "memory management", "oop", "cheatsheet"],
    url: "https://learn.codeunia.com/cpp",
    subject: "C++",
    cheatsheetName: "C++ Programming Cheatsheet",
    markdownFile: "cpp.md",
  },
  csharp: {
    title: "C# Programming Cheatsheet",
    description: "Master C# for web and game development with .NET.",
    keywords: ["csharp", "c#", ".net", "programming", "cheatsheet"],
    url: "https://learn.codeunia.com/csharp",
    subject: "C#",
    cheatsheetName: "C# Programming Cheatsheet",
    markdownFile: "csharp.md",
  },
  css: {
    title: "CSS Cheatsheet — Codeunia",
    description: "Master CSS styling, layouts, animations, and modern CSS features for responsive web design and user interfaces.",
    keywords: ["css", "styling", "layout", "flexbox", "grid", "animations", "responsive design", "web development"],
    url: "https://learn.codeunia.com/css",
    subject: "CSS",
    cheatsheetName: "CSS Cheatsheet",
    markdownFile: "css.md",
  },
  docker: {
    title: "Docker Cheatsheet — Codeunia",
    description: "Containerization with Docker, from basic containers to multi-stage builds and orchestration. Complete Docker reference guide.",
    keywords: ["docker", "containers", "dockerfile", "compose", "devops", "containerization", "cheatsheet"],
    url: "https://learn.codeunia.com/docker",
    subject: "Docker",
    cheatsheetName: "Docker Cheatsheet",
    markdownFile: "docker.md",
  },
  flutter: {
    title: "Flutter Development Cheatsheet",
    description: "Comprehensive Flutter development guide with widgets, state management, animations, and mobile app development.",
    keywords: ["flutter", "dart", "mobile development", "android", "ios", "cross platform"],
    url: "https://learn.codeunia.com/flutter",
    subject: "Flutter",
    cheatsheetName: "Flutter Development Cheatsheet",
    markdownFile: "flutter.md",
  },
  git: {
    title: "Git Cheatsheet — Codeunia",
    description: "Master Git version control with essential commands, branching strategies, and collaboration workflows for software development.",
    keywords: ["git", "version control", "github", "branching", "collaboration", "development tools", "workflow"],
    url: "https://learn.codeunia.com/git",
    subject: "Git",
    cheatsheetName: "Git Cheatsheet",
    markdownFile: "git.md",
  },
  go: {
    title: "Go Programming Cheatsheet — Codeunia",
    description: "Modern programming with Go, featuring concurrency, simplicity, and performance. Complete Go reference guide.",
    keywords: ["go", "golang", "programming", "concurrency", "goroutines", "channels", "cheatsheet"],
    url: "https://learn.codeunia.com/go",
    subject: "Go",
    cheatsheetName: "Go Programming Cheatsheet",
    markdownFile: "go.md",
  },
  html: {
    title: "HTML5 Cheatsheet — Codeunia",
    description: "Structure web content with semantic HTML5 elements, forms, and accessibility features. Complete HTML reference guide.",
    keywords: ["html", "html5", "semantic", "forms", "accessibility", "web development", "cheatsheet"],
    url: "https://learn.codeunia.com/html",
    subject: "HTML",
    cheatsheetName: "HTML5 Cheatsheet",
    markdownFile: "html.md",
  },
  java: {
    title: "Java Cheatsheet — Codeunia",
    description: "Learn Java programming fundamentals including OOP concepts, data structures, and enterprise development patterns.",
    keywords: ["java", "programming", "oop", "object oriented", "data structures", "enterprise", "spring"],
    url: "https://learn.codeunia.com/java",
    subject: "Java",
    cheatsheetName: "Java Cheatsheet",
    markdownFile: "java.md",
  },
  javascript: {
    title: "JavaScript Cheatsheet — Codeunia",
    description: "Master modern JavaScript with ES6+ features, async programming, and DOM manipulation. Complete JavaScript reference guide.",
    keywords: ["javascript", "js", "es6", "programming", "web development", "cheatsheet"],
    url: "https://learn.codeunia.com/javascript",
    subject: "JavaScript",
    cheatsheetName: "JavaScript Cheatsheet",
    markdownFile: "javascript.md",
  },
  kotlin: {
    title: "Kotlin Programming Cheatsheet",
    description: "Comprehensive Kotlin programming guide with syntax, Android development, coroutines, and best practices.",
    keywords: ["kotlin", "android", "jvm", "programming", "coroutines"],
    url: "https://learn.codeunia.com/kotlin",
    subject: "Kotlin",
    cheatsheetName: "Kotlin Programming Cheatsheet",
    markdownFile: "kotlin.md",
  },
  linux: {
    title: "Linux Command Line Cheatsheet — Codeunia",
    description: "Command line mastery with Linux commands, shell scripting, and system administration. Complete Linux reference guide.",
    keywords: ["linux", "bash", "shell", "command line", "terminal", "system administration", "cheatsheet"],
    url: "https://learn.codeunia.com/linux",
    subject: "Linux",
    cheatsheetName: "Linux Command Line Cheatsheet",
    markdownFile: "linux.md",
  },
  mongodb: {
    title: "MongoDB Cheatsheet",
    description: "A comprehensive guide to MongoDB commands and operations.",
    keywords: ["mongodb", "database", "nosql", "cheatsheet"],
    url: "https://learn.codeunia.com/mongodb",
    subject: "MongoDB",
    cheatsheetName: "MongoDB Cheatsheet",
    markdownFile: "mongodb.md",
  },
  nodejs: {
    title: "Node.js Cheatsheet — Codeunia",
    description: "Learn Node.js server-side JavaScript development, APIs, modules, npm packages, and backend development fundamentals.",
    keywords: ["nodejs", "node.js", "javascript", "backend", "server", "api", "npm", "web development"],
    url: "https://learn.codeunia.com/nodejs",
    subject: "Node.js",
    cheatsheetName: "Node.js Cheatsheet",
    markdownFile: "nodejs.md",
  },
  postgresql: {
    title: "PostgreSQL Cheatsheet",
    description: "A comprehensive guide to PostgreSQL commands and operations.",
    keywords: ["postgresql", "database", "sql", "cheatsheet"],
    url: "https://learn.codeunia.com/postgresql",
    subject: "PostgreSQL",
    cheatsheetName: "PostgreSQL Cheatsheet",
    markdownFile: "postgresql.md",
  },
  python: {
    title: "Python Cheatsheet — Codeunia",
    description: "Learn Python fundamentals, data structures, and popular frameworks for web development. Complete Python programming reference.",
    keywords: ["python", "programming", "data structures", "web development", "cheatsheet", "tutorial"],
    url: "https://learn.codeunia.com/python",
    subject: "Python",
    cheatsheetName: "Python Cheatsheet",
    markdownFile: "python.md",
  },
  react: {
    title: "React Cheatsheet — Codeunia",
    description: "Master React fundamentals including components, hooks, state management, and modern React patterns for building web applications.",
    keywords: ["react", "javascript", "components", "hooks", "state management", "frontend", "web development"],
    url: "https://learn.codeunia.com/react",
    subject: "React",
    cheatsheetName: "React Cheatsheet",
    markdownFile: "react.md",
  },
  rust: {
    title: "Rust Programming Cheatsheet",
    description: "A comprehensive guide to Rust programming concepts.",
    keywords: ["rust", "programming", "cheatsheet"],
    url: "https://learn.codeunia.com/rust",
    subject: "Rust",
    cheatsheetName: "Rust Programming Cheatsheet",
    markdownFile: "rust.md",
  },
  sql: {
    title: "SQL Cheatsheet — Codeunia",
    description: "Learn SQL database fundamentals including queries, joins, functions, and database design for data management and analysis.",
    keywords: ["sql", "database", "queries", "joins", "data analysis", "mysql", "postgresql", "sqlite"],
    url: "https://learn.codeunia.com/sql",
    subject: "SQL",
    cheatsheetName: "SQL Cheatsheet",
    markdownFile: "sql.md",
  },
  swift: {
    title: "Swift Programming Cheatsheet",
    description: "Comprehensive Swift programming guide with syntax, SwiftUI, iOS development, and best practices.",
    keywords: ["swift", "ios", "swiftui", "apple", "programming", "mobile"],
    url: "https://learn.codeunia.com/swift",
    subject: "Swift",
    cheatsheetName: "Swift Programming Cheatsheet",
    markdownFile: "swift.md",
  },
  typescript: {
    title: "TypeScript Cheatsheet — Codeunia",
    description: "Master TypeScript types, interfaces, generics, and advanced features for type-safe JavaScript development.",
    keywords: ["typescript", "javascript", "types", "interfaces", "generics", "type safety", "web development"],
    url: "https://learn.codeunia.com/typescript",
    subject: "TypeScript",
    cheatsheetName: "TypeScript Cheatsheet",
    markdownFile: "typescript.md",
  },
  vue: {
    title: "Vue.js 3 Cheatsheet — Codeunia",
    description: "Progressive framework for building user interfaces with Vue 3 and Composition API. Complete Vue.js reference guide.",
    keywords: ["vue", "vuejs", "vue3", "composition api", "javascript", "frontend", "framework", "cheatsheet"],
    url: "https://learn.codeunia.com/vue",
    subject: "Vue.js",
    cheatsheetName: "Vue.js 3 Cheatsheet",
    markdownFile: "vue.md",
  },
};
